#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Creating VM B with default settings in resource group $RG"
#
set -x
#
az vm create \
 --resource-group $RG \
 --name B \
 --image UbuntuLTS \
 --admin-username azure \
 --ssh-key-value ~/.ssh/id_rsa.pub
