#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Create network B and subnet B1 resource group $RG"
#
set -x
#
# Create VNet and first subnet
#
az network vnet create \
  --resource-group $RG \
  --name Net-B \
  --address-prefixes 172.17.0.0/16 
#
# Create first subnet
#
az network vnet subnet create \
  --resource-group $RG \
  --vnet-name Net-B \
  --name B1 \
  --address-prefixes 172.17.7.0/24
