#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Create virtual machines A1 and A2 in Net-A and B1 in Net-B in resource group $RG"
#
set -x
#
az vm create \
 --resource-group $RG \
 --name A1 \
 --image UbuntuLTS \
 --vnet-name Net-A \
 --subnet A1 \
 --admin-username azure \
 --ssh-key-value ~/.ssh/id_rsa.pub \
 --public-ip-address Public_A1 
#
az vm create \
 --resource-group $RG \
 --name A2 \
 --image UbuntuLTS \
 --vnet-name Net-A \
 --subnet A2 \
 --admin-username azure \
 --ssh-key-value ~/.ssh/id_rsa.pub \
 --public-ip-address Public_A2 
#
az vm create \
 --resource-group $RG \
 --name B1 \
 --image UbuntuLTS \
 --vnet-name Net-B \
 --subnet B1 \
 --admin-username azure \
 --public-ip-address Public_B1 
