#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Create A and subnets A1 and A2 in resource group $RG"
#
set -x
#
# Create VNet and first subnet
#
az network vnet create \
  --resource-group $RG \
  --name Net-A \
  --address-prefixes 172.16.0.0/16 
#
# Create first subnet
#
az network vnet subnet create \
  --resource-group $RG \
  --vnet-name Net-A \
  --name A1 \
  --address-prefixes 172.16.1.0/24
#
# Create second subnet
#
az network vnet subnet create \
  --resource-group $RG \
  --vnet-name Net-A \
  --name A2 \
  --address-prefixes 172.16.2.0/24
