#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Create peering between networks A and B in resource group $RG"
#
set -x
#
# Create A-to-B peering
#
az network vnet peering create \
  --name A2B --resource-group $RG \
  --vnet-name Net-A --remote-vnet Net-B
#
# Create B-to-A
#
az network vnet peering create \
  --name B2A --resource-group $RG \
  --vnet-name Net-B --remote-vnet Net-A
