#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Apply NSG to resource group $RG"
set -x
#
# Apply NSG to subnets
#
az network vnet subnet update \
  --resource-group $RG --vnet-name AppNet --name DBSubnet \
  --network-security-group "DB-NSG"
#
az network vnet subnet update \
  --resource-group $RG --vnet-name AppNet --name AppSubnet \
  --network-security-group "Web-NSG"
