#!/bin/bash
RG=`cat ~/.rg 2>/dev/null`
RG=${RG:-Test}
echo "Create VMs in App- and DB subnet, resource group $RG"
set -x
#
az vm create \
 --resource-group $RG \
 --name Web \
 --image UbuntuLTS \
 --vnet-name AppNet \
 --subnet AppSubnet --nsg "" \
 --admin-username azure \
 --ssh-key-value ~/.ssh/id_rsa.pub \
 --public-ip-address Public_Web
#
az vm create \
 --resource-group $RG \
 --name DB \
 --image UbuntuLTS \
 --vnet-name AppNet \
 --subnet DBSubnet --nsg "" \
 --admin-username azure \
 --ssh-key-value ~/.ssh/id_rsa.pub \
 --public-ip-address ""
