# main ansible playbook to provision instances from dynamic inventory
---
- hosts: webserver
  gather_facts: False
  
  tasks:
    - name: Upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        
    - name: Update cache
      become: yes
      apt:  
        update_cache: yes

    - name: Install Apache on ubuntu
      apt: 
        name: apache2
        state: latest 
      become: yes
    
    - name: Enable includes and cgi
      become: yes  
      command:
        cmd: a2enmod include cgi
      

    - name: Copy .htaccess
      copy:
        src: "webserver/.htaccess"
        dest: "/var/www/html/.htaccess"
      become: yes
      
    - name: Enable xbithack in apache2.conf
      become: yes
      lineinfile:
        path: "/etc/apache2/apache2.conf"
        insertafter: EOF
        line: "XBitHack on"
        state: present
      
    
    - name: Modify directory in apache2.conf
      become: yes
      lineinfile:
        path: "/etc/apache2/apache2.conf"
        regexp: 'Options Indexes FollowSymLinks'
        firstmatch: yes
        line: "\tOptions Indexes FollowSymLinks Includes"
    
    - name: copy index.html and modify permission
      copy:
        src: "webserver/index.html"
        dest: "/var/www/html/index.html"
        mode: a+x
      become: yes
      notify: restart apache2
    
  handlers:
    - name: restart apache2
      service:
        name: apache2
        enabled: yes
        state: restarted
      become: yes